### ISSUE TITLE
Ignoring invalid task provided offset -- not yet consumed

### ISSUE THREAD

**Issue by alexnikitchuk** [snowflakedb/snowflake-kafka-connector#820] opened 2024-04-09 17:01 UTC
We faced a very interesting issue: after switching Kafka Connect to the backup Kafka cluster Snowflake connectors started to log warnings:
```
[2024-04-09 16:46:49,804] WARN WorkerSinkTask{id=topic-name-0} Ignoring invalid task provided offset topic-name-0/OffsetAndMetadata{offset=13054, leaderEpoch=null, metadata=''} -- not yet consumed, taskOffset=13054 currentOffset=466 (org.apache.kafka.connect.runtime.WorkerSinkTask)
```
Looks like it is caused by offset discrepancies between clusters. 
Our idea is to continue writing data to the same Snowflake table but from the backup cluster and start reading from the latest offsets to avoid data duplication.

Any ideas on how to achieve it?

**Comment by sfc-gh-wfateem** [comment] 2024-04-09 17:11
Hi @alexnikitchuk,
I think your issue is best addressed from a Kafka perspective by your Kafka vendor. Your main problem here is that the offsets on Cluster A and offsets on Cluster B are not matching. You're going to have the problem of replicating topics with the exact same offsets and making sure that when you failover to your backup cluster, both topics are identical in terms of the log's end-offset. In addition to this, you would need to make sure that the consumer group offset has also been replicated and is in sync with the source cluster when failing over. 
To your question, if you're using Snowpipe Streaming as the ingestion method then you shouldn't worry about data duplication because we would be using the offset stored on our end, if you try to send offsets lower than that then those are ignored.
Once you have a discrepancy with the offsets like the one you're showing, then Kafka is going to reset the consumer's offset to either the earliest available position in your topic or to the latest position in the topic. With the reset offset policy of latest you may run into the issue of missing data from your topic.

**Comment by alexnikitchuk** [comment] 2024-04-09 17:27
thanks for the quick response @sfc-gh-wfateem !
> Once you have a discrepancy with the offsets like the one you're showing, then Kafka is going to reset the consumer's offset to either the earliest available position in your topic or to the latest position in the topic. With the reset offset policy of latest you may run into the issue of missing data from your topic.

Well, it does not reset offsets, just logs warnings and does not consume any messages

**Comment by sfc-gh-wfateem** [comment] 2024-04-09 17:36
So with respect to the offset (13054) we're asking Kafka to start consuming from, what's the last committed offset recorded for this consumer group in your new cluster and what's the log end-offset?
Have you also confirmed that there are messages in the topic-partitions?

**Comment by alexnikitchuk** [comment] 2024-04-26 07:46
Not at this time,
We will try to sync offsets properly.
Thanks.

**Comment by sfc-gh-wfateem** [comment] 2024-04-26 21:42
Sounds good.
I will go ahead and close this. 
Feel free to reach out again if you have any other issues.

**Closed by sfc-gh-wfateem** 2024-04-26 21:42 UTC

**Comment by reason1241** [comment] 2024-07-18 06:59
I reset my Kafka offset and discarded the older one. Now, the new Kafka offset starts from 0, and Snowflake Kafka connectors don't ingest the messages at all, showing the given error message. Can I reset the Snowpipe Streaming offset? Is it fine for me to do that?

**Comment by reason1241** [comment] 2024-07-18 08:00
I reset my Snowflake channel's offset but it doesn't work. I can see the offset as 0 on Snowflake web console(Snowsight), though my Snowflake connector still recognizes the previous offset.
