### ISSUE TITLE
Connectors tasks do not FAIL with `break.on.schema.registry.error=true`

### ISSUE THREAD

**Issue by aidan-melen** [snowflakedb/snowflake-kafka-connector#538] opened 2023-02-08 16:32 UTC
I enabled `break.on.schema.registry.error=true` for a connector with an AVRO value. The logs shows lots of `ERROR` messages in the form of:

```
[ERROR] 2023-02-08 16:25:14,569 [task-thread-my-connector-1] com.snowflake.kafka.connector.records.SnowflakeConverter error - [SF_KAFKA_CONNECTOR] [KC:548647920] failed to parse AVRO record
```

With this, I would expect the connector task to enter a `FAILED` state and stop consumption. However, the connector state shows a `RUNNING` status for the connector and all tasks:

```
$ kc config my-connector | jq -S
{
    "connector.class": "com.snowflake.kafka.connector.SnowflakeSinkConnector",
    "key.converter": "com.snowflake.kafka.connector.records.SnowflakeAvroConverter",
    "key.converter.schema.registry.url": "https://schemaregistry:8081",
    "key.converter.schemas.enable": "true",
    "name": "my-connector",
    "topics": "my-topic",
    "value.converter": "com.snowflake.kafka.connector.records.SnowflakeAvroConverter",
    "value.converter.break.on.schema.registry.error": "true",
    "value.converter.schema.registry.url": "https://schemaregistry:8081",
    "value.converter.schemas.enable": "true"
    ...
}

$ kc status my-connector | jq
{
  "my-connector": {
    "status": {
      "name": "my-connector",
      "connector": {
        "state": "RUNNING",
        "worker_id": "connect:8083"
      },
      "tasks": [
        {
          "id": 0,
          "state": "RUNNING",
          "worker_id": "connect:8083"
        },
        {
          "id": 1,
          "state": "RUNNING",
          "worker_id": "connect:8083"
        },
        {
          "id": 2,
          "state": "RUNNING",
          "worker_id": "connect:8083"
        }
      ],
      "type": "sink"
    }
  }
```

**Comment by aidan-melen** [comment] 2023-02-08 16:53
> If loading Avro data from the Schema Registry Service, this property determines if the Kafka connector should stop consuming records if it encounters an error while fetching the schema id

So does this mean it will `ERROR` but not enter a `FAILED` state. This is problematic because we cannot check for failure use the connector/task status. Instead, we must rely on alerting of logs.

**Comment by sfc-gh-japatel** [comment] 2023-02-09 00:35
Thanks for bringing this up. I will take a look at this.

**Comment by sfc-gh-japatel** [comment] 2023-02-10 00:15
I took a look at the code and it seems like this is by design, we will take this as a feature request. 
But on a side note, why are we not able to retrived the schema by id? Can you make sure you have schema id in your record?

**Comment by sfc-gh-japatel** [comment] 2023-02-24 00:38
Closing this as this was the expected behavior but we hear your concerns. Here is the summary of discussion happened:
1. We understand why the default was set to false and in hindisight, this could have set to true as well. Setting it to true would mean there would be a silent data loss if retention time was much low in kafka or no monitoring on connector side. 
2. We will think about potentially batching our put operations in snowpipe based Kafka connector. 
3. We might as well look into killing the snowflake connector on other fatal issues which is what the ask is. 

Overall, we anticipate less errors because of Snowflake converters since we will not support them in Snowpipe Streaming. 

Thanks @aidan-melen

**Closed** 2023-02-24 00:39 UTC
