### ISSUE TITLE
Snowpipe Streaming Duplicate records / Not Exactly Once

### ISSUE THREAD

**Issue by imrohankataria** [snowflakedb/snowflake-kafka-connector#710] opened 2023-09-26 16:49 UTC
Hi, 

PROD DATA GETTING DUPLICATES!!!

Using Snowflake Sink Connector to get my data from Eventhub to Snowflake, but Im experiencing duplicate records, entire set getting copied again.

Configuration used for Snowflake Sink Connector -
```
spec:
  autoRestart:
    enabled: true
  class: com.snowflake.kafka.connector.SnowflakeSinkConnector
  config:
    buffer.count.records: 10000
    buffer.flush.time: 60
    buffer.size.bytes: 5000000
    snowflake.database.name: DB
    snowflake.ingestion.method: SNOWPIPE_STREAMING
    snowflake.private.key: ${env:KEY}
    snowflake.private.key.passphrase: ${env:KEY}
    snowflake.role.name: ROLE
    snowflake.schema.name: SCHEMA
    snowflake.topic2table.map: 38 TOPICS
    snowflake.url.name:URL
    snowflake.user.name: USER
    topics: 38 TOPICS
  pause: true
  tasksMax: 38
```

Using JDBC Source Connector

<img width="540" alt="image" src="https://github.com/snowflakedb/snowflake-kafka-connector/assets/41874450/3222ec50-b594-4a51-9a91-b33a1df58904">

**Comment by sfc-gh-japatel** [comment] 2023-09-26 17:11
Thanks
Few questions:

1. Will you be willing to share some logs along the timeline where you experienced duplicates? 
2. Where have you seen duplicates? In kafka table on snowflake side?

**Comment by imrohankataria** [comment] 2023-09-26 17:41
What exact you'd like to see? I can do a grep and get you exact logs

**Comment by imrohankataria** [comment] 2023-09-26 17:46
Duplicate in Kafka Snowflake tables (where it dumps data in snowflake) @sfc-gh-japatel

**Comment by imrohankataria** [comment] 2023-09-26 17:55
Entire log would be huge, but if you can comment what exactly needs to be seen in logs? I can do a grep and get exact what you need
version - 2.0.0

**Comment by sfc-gh-japatel** [comment] 2023-09-26 18:06
Few more questions/asks:
1. Can you use latest version https://github.com/snowflakedb/snowflake-kafka-connector/releases/tag/v2.0.1
2. Can you repro this issue everytime? 
3. Logs around the time you see duplicate candidates in your table in SF. I want to see where because of which exception this is occurring.

**Comment by imrohankataria** [comment] 2023-09-26 18:33
One thing I want to mention,

I try to reload data a lot of times, and what I do is recreate sink connector with new name, so it loads from beginning of the topic.
I dont change the base table name in snowflake, so it always puts data in same table, from same kafka topic, but a different sink connector name.

**Comment by sfc-gh-japatel** [comment] 2023-09-26 18:36
I see, well this might be one of the reasons why you see duplicates. Can you always choose a new table in snowflake? 

Also we have had bug in 2.0.0 which got fixed in 2.0.1 which could see missing data if you have lot of rebalances. 
We havent seen duplicate issue but what you mention could be the reason.

**Comment by imrohankataria** [comment] 2023-09-26 18:41
Again, The Way I have setted up the whol setup is, there are streams on top of tables.
Issue is what Im seeing on Kafka Broker/Eventhub, Data going out x2 times.

**Comment by imrohankataria** [comment] 2023-09-26 19:02
Hope it doesn't have to do anything with the Offset resetting. 
Also if there is a network error, doesn't it have to check the offset value before reloading data?

**Comment by sfc-gh-japatel** [comment] 2023-09-27 17:46
Wo do that today! please verify from snowflake side that offset is ingested twice on your landing table.

**Comment by imrohankataria** [comment] 2023-09-27 18:18
How to check?

**Comment by sfc-gh-japatel** [comment] 2023-09-27 18:30
https://docs.snowflake.com/en/user-guide/kafka-connector-overview#schema-of-tables-for-kafka-topics

Here is what I use

```
select 
record_metadata:"topic"::string as TOPIC, 
record_metadata:"partition"::number as PARTITION_NO,
count(distinct record_metadata:"offset"::number) as unique_offsets_per_partition,
count(record_metadata:"offset"::number) as count_per_partitions,
min(record_metadata:"offset"::number) as min_offset,
max(record_metadata:"offset"::number) as max_offset,
(max_offset-min_offset+1) as diff_min_max_offsets,
case diff_min_max_offsets-unique_offsets_per_partition
    when 0 then 'Nothing Missing'
    else 'Missing Data/Duplicate Data'
    end as data_completeness
from <base_table>
group by TOPIC, PARTITION_NO
order by PARTITION_NO
;
```

**Comment by sfc-gh-japatel** [comment] 2023-11-14 19:06
Hi @imrohankataria closing this since there has been no activity, feel free to open again with more details on how you were able to reproduce duplicate data. We would definitely take that as a priority. thanks

**Closed by sfc-gh-japatel** 2023-11-14 19:06 UTC
